import 'dart:io';
import 'package:intl/intl.dart';
import '../models/album.dart';
import '../models/photo.dart';
import 'database_service.dart';
import 'auth_service.dart';

class AlbumService {
  static final AlbumService instance = AlbumService._init();
  AlbumService._init();

  final DatabaseService _db = DatabaseService.instance;
  final AuthService _auth = AuthService.instance;

  Future<Album> getOrCreateDailyAlbum() async {
    final userId = _auth.currentUser!.id!;
    final todayName = DateFormat('dd.MM.yyyy').format(DateTime.now());

    Album? existingAlbum = await _db.getAlbumByNameAndDate(userId, todayName);

    if (existingAlbum != null) {
      return existingAlbum;
    }

    final newAlbum = Album(
      name: todayName,
      userId: userId,
      createdAt: DateTime.now(),
      isAutoGenerated: true,
    );

    return await _db.createAlbum(newAlbum);
  }

  Future<Album> createManualAlbum(
    String name, {
    int autoDeleteDays = 0,
    bool deleteAlbumWithPhotos = false,
  }) async {
    final userId = _auth.currentUser!.id!;

    final album = Album(
      name: name,
      userId: userId,
      createdAt: DateTime.now(),
      isAutoGenerated: false,
      autoDeleteDays: autoDeleteDays,
      deleteAlbumWithPhotos: deleteAlbumWithPhotos,
    );

    return await _db.createAlbum(album);
  }

  Future<List<Album>> getUserAlbums() async {
    final userId = _auth.currentUser!.id!;
    return await _db.getAlbumsByUserId(userId);
  }

  Future<List<Photo>> getAlbumPhotos(int albumId) async {
    return await _db.getPhotosByAlbumId(albumId);
  }

  Future<Photo> addPhotoToAlbum(String photoPath, int albumId, {bool isVideo = false}) async {
    final userId = _auth.currentUser!.id!;
    final userName = _auth.currentUser!.name;

    final photo = Photo(
      path: photoPath,
      albumId: albumId,
      userId: userId,
      takenAt: DateTime.now(),
      takenBy: userName,
      isVideo: isVideo,
    );

    return await _db.createPhoto(photo);
  }
  
  Future<bool> toggleFavorite(int photoId, bool isFavorite) async {
    try {
      await _db.updatePhotoFavorite(photoId, isFavorite);
      return true;
    } catch (e) {
      print('Favori güncelleme hatası: $e');
      return false;
    }
  }

  Future<bool> deleteAlbum(int albumId) async {
    try {
      await _db.deleteAlbum(albumId);
      return true;
    } catch (e) {
      print('Albüm silme hatası: $e');
      return false;
    }
  }

  Future<bool> deletePhoto(int photoId) async {
    try {
      await _db.deletePhoto(photoId);
      return true;
    } catch (e) {
      print('Fotoğraf silme hatası: $e');
      return false;
    }
  }

  Future<bool> updateAlbum(Album album) async {
    try {
      await _db.updateAlbum(album);
      return true;
    } catch (e) {
      print('Albüm güncelleme hatası: $e');
      return false;
    }
  }

  Future<Album?> getAlbumById(int id) async {
    return await _db.getAlbumById(id);
  }

  int _convertToHours(int value) {
    if (value == -1) return -1;
    if (value == 0) return 720;
    if (value == 1) return 24;
    if (value == 3) return 72;
    if (value == 7) return 168;
    if (value == 30) return 720;
    if (value == 90) return 2160;
    if (value == 365) return 8760;
    if ([12, 24, 72, 168, 720, 2160, 8760].contains(value)) return value;
    return 720;
  }

  Future<void> performAutoDelete() async {
    final userId = _auth.currentUser!.id!;
    final albums = await _db.getAlbumsByUserId(userId);
    final now = DateTime.now();

    int deletedPhotosCount = 0;
    int deletedAlbumsCount = 0;

    for (final album in albums) {
      int hoursToKeep = _convertToHours(album.autoDeleteDays);
      
      if (hoursToKeep == -1) continue;

      final photos = await _db.getPhotosByAlbumId(album.id!);
      bool allPhotosDeleted = true;
      int albumDeletedCount = 0;

      for (final photo in photos) {
        final difference = now.difference(photo.takenAt).inHours;
        
        if (difference >= hoursToKeep) {
          try {
            final file = File(photo.path);
            if (await file.exists()) {
              await file.delete();
            }
            
            await _db.deletePhoto(photo.id!);
            albumDeletedCount++;
            deletedPhotosCount++;
          } catch (e) {
            print('Otomatik silme hatası (Foto ID: ${photo.id}): $e');
            allPhotosDeleted = false;
          }
        } else {
          allPhotosDeleted = false;
        }
      }

      if (allPhotosDeleted && albumDeletedCount > 0 && album.deleteAlbumWithPhotos) {
        try {
          await _db.deleteAlbum(album.id!);
          deletedAlbumsCount++;
          print('Albüm silindi: ${album.name}');
        } catch (e) {
          print('Albüm silme hatası: $e');
        }
      }
    }

    if (deletedPhotosCount > 0) {
      print('$deletedPhotosCount adet eski fotoğraf otomatik olarak silindi.');
    }
    if (deletedAlbumsCount > 0) {
      print('$deletedAlbumsCount adet boş albüm otomatik olarak silindi.');
    }
  }
}
