class Album {
  final int? id;
  final String name;
  final int userId;
  final DateTime createdAt;
  final bool isAutoGenerated;
  final int autoDeleteDays;
  final bool deleteAlbumWithPhotos;

  Album({
    this.id,
    required this.name,
    required this.userId,
    required this.createdAt,
    this.isAutoGenerated = false,
    this.autoDeleteDays = 0,
    this.deleteAlbumWithPhotos = false,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'user_id': userId,
      'created_at': createdAt.toIso8601String(),
      'is_auto_generated': isAutoGenerated ? 1 : 0,
      'auto_delete_days': autoDeleteDays,
      'delete_album_with_photos': deleteAlbumWithPhotos ? 1 : 0,
    };
  }

  factory Album.fromMap(Map<String, dynamic> map) {
    return Album(
      id: map['id'],
      name: map['name'],
      userId: map['user_id'],
      createdAt: DateTime.parse(map['created_at']),
      isAutoGenerated: map['is_auto_generated'] == 1,
      autoDeleteDays: map['auto_delete_days'] ?? 0,
      deleteAlbumWithPhotos: map['delete_album_with_photos'] == 1,
    );
  }

  Album copyWith({
    int? id,
    String? name,
    int? userId,
    DateTime? createdAt,
    bool? isAutoGenerated,
    int? autoDeleteDays,
    bool? deleteAlbumWithPhotos,
  }) {
    return Album(
      id: id ?? this.id,
      name: name ?? this.name,
      userId: userId ?? this.userId,
      createdAt: createdAt ?? this.createdAt,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      autoDeleteDays: autoDeleteDays ?? this.autoDeleteDays,
      deleteAlbumWithPhotos: deleteAlbumWithPhotos ?? this.deleteAlbumWithPhotos,
    );
  }
}
